# Use an official Python runtime as a base image
FROM --platform=linux/amd64 python:3.9

# Set the working directory inside the container
WORKDIR /app

# Copy everything from the local directory to the container
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the correct port for Cloud Run
EXPOSE 8080

# Start the Flask application using Gunicorn
CMD ["gunicorn", "-b", "0.0.0.0:8080", "dialogflow_tools.playbook_tool_webhook:app"]
