openapi: 3.0.1
info:
  title: Abandoned Vehicle Reporter
  description: Obtains information to file a case for an abandoned vehicle
  version: 1.0.0
servers:
  - url: https://da77-130-86-76-140.ngrok-free.app
paths:
  /file-abandoned-vehicle:
    post:
      summary: Information on the abandoned vehicle to post to SalesForce
      operationId: vehicleData
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                make:
                  type: string
                  example: "Honda"
                model:
                  type: string
                  example: "Civic"
                vehicleColor: 
                  type: string
                  example: "blue"
                licensePlate:
                  type: string
                  example: "6LIK274"
                timePeriod:
                  type: integer
                  example: "12"
                location:
                  type: string
                  example: "123 Avenue Street"
                firstName: 
                  type: string
                  nullable: true
                  example: "John"
                lastName:
                  type: string
                  nullable: true
                  example: "Doe"
                phoneNumber:
                  type: string
                  nullable: true
                  example: "123-456-7890"
      responses:
        "200":
          description: Abandoned vehicle case successfully posted to Salesforce
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  caseId:
                    type: string
        "401":
          description: Abandoned vehicle case unsuccessful, address is outside of Sacramento area
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error: 
                    type: string
        "500":
          description: Abandoned vehicle case unsuccessful, server error occurred
          content:
            application/json:
              schema:
                type: object
                properties: 
                  success:
                    type: boolean
                  error: 
                    type: string
        

        