openapi: 3.0.1
info:
  title: Dead Animal Reporting Tool
  description: Fills out required information for a dead animal case. 
  version: 1.0.0
servers: 
  - url:  https://54c3-76-14-184-190.ngrok-free.app
paths: 
  /dead_animal:
    post: 
      summary: Make a new dead animal case.
      operationId: createDeadAnimal # This is just an indentifier for the operation, NOT a schema reference.
      requestBody: 
        required: true
        content: 
          application/json:
            schema:
              type: object
              properties: 
                location: 
                  type: string
                  enum:
                    - Right of Way
                    - Private Property
                  description: Location of dead animal. Must be either "Right of Way" or "Private Property".
                animalType:
                  type: string
                  enum: 
                    - Bird
                    - Cat
                    - Dog
                    - Livestock
                    - Other
                    - Poultry
                  description: The type of animal. Must be either "Bird", "Cat", "Dog", "Livestock", "Other", or "Poultry".
                animalTotal:
                  type: integer
                  description: The number of dead animals.
                firstName:
                  type: string
                  nullable: true
                  example: "Bob"
                lastName: 
                  type: string
                  nullable: true
                  example: "Doe"
                phoneNumber:
                  type: string
                  nullable: true
                  example: "235-895-9844"
      responses:
        '200':
          description: Successfully made new dead animal case. 
        '400':
          description: Invalid or missing data.