openapi: 3.0.1
info:
  title: Salesforce Integration API
  description: API to push Dialogflow CX user data into Salesforce
  version: 1.0.0

servers:
  - url:  https://ba48-76-14-184-190.ngrok-free.app  # Replace with your actual Flask API URL

paths:
  /generic-case-post:
    post:
      summary: Push user data from Dialogflow CX to Salesforce
      operationId: pushToSalesforce
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SalesforceRequest"
      responses:
        '200':
          description: Successfully pushed to Salesforce
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SalesforceResponse"
        '400':
          description: Invalid request
        '401':
          description: Address outside of service area
        '500':
          description: Server error

components:
  schemas:
    SalesforceRequest:
      type: object
      properties:
        firstName:
          type: string
          nullable: true
          description: "First name of the user, empty if anonymous"
          example: "John"
        lastName:
          type: string
          nullable: true
          description: "Last name of the user, empty if anonymous"
          example: "Doe"
        phone:
          type: string
          nullable: true
          description: "User's phone number, '0' if anonymous"
          example: "123-456-7890"
        issueType:
          type: string
          description: "The type of issue being reported"
          example: "Service Disruption"
        description:
          type: string
          description: "Details of the issue"
          example: "Internet outage in my area."
        address:
          type: string
          description: "Address for the issue"
          example: "123 J street"

    SalesforceResponse:
      type: object
      properties:
        success:
          type: boolean
          description: "Indicates whether the report was successfully pushed"
        salesforce_response:
          type: object
          description: "Full response from Salesforce"